server:
  port: 8081
  servlet:
    context-path: /api
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
corsPaths: "/**"
imageDir: "C:/images"
####### resource server configuration properties
spring:
  security:
    basic:
      enabled: false
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/SpringBootKeycloak
          jwk-set-uri: http://localhost:8080/auth/realms/SpringBootKeycloak/protocol/openid-connect/certs
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/orclpdb1
    username: lem_stage
    password: lem_stage
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
      poolName: HikariPoolBooks

  jpa:
    database: oracle
    database-platform: org.hibernate.dialect.Oracle12cDialect
    generate-ddl: true
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
relationshipLabels:
  #key, value(M), value(F)
  - wife,husband,wife
  - husband,husband,wife
  - bestfriend
  - ex
  - boyfriend,boyfriend,girlfriend
  - girlfriend,boyfriend,girlfriend
  - ninong,inaanak,inaanak
  - ninang,inaanak,inaanak
  - inaanak,ninong,ninang
  - barkada
  - partner

logging:
  level:
    org:
      springframework:
        security: DEBUG