server:
  port: 8083
  servlet:
    context-path: /api
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
corsPaths: "/**"
imageDir: "C:/images"
####### resource server configuration properties
spring:
  security:
    basic:
      enabled: false
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/SpringBootKeycloak
          jwk-set-uri: http://localhost:8080/auth/realms/SpringBootKeycloak/protocol/openid-connect/certs
  datasource:
    username: lem
    password: lem
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/h2taeza1
    #url: jdbc:h2:mem:testdb
  h2:
    console.enabled: true
  jpa:
    database: oracle
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
relationshipLabels:
  #key, value(M), value(F)
  - wife,husband,wife
  - husband,husband,wife
  - bestfriend
  - ex
  - boyfriend,boyfriend,girlfriend
  - girlfriend,boyfriend,girlfriend
  - ninong,inaanak,inaanak
  - ninang,inaanak,inaanak
  - inaanak,ninong,ninang
  - barkada
  - partner

logging:
  level:
    org:
      springframework:
        security: DEBUG