 alter session set container = XEPDB1;
CREATE USER lem IDENTIFIED BY lem;
GRANT CONNECT TO lem;
GRANT CONNECT, RESOURCE, DBA TO lem;
GRANT CREATE SESSION to lem ;
GRANT ALL PRIVILEGES TO lem;
GRANT UNLIMITED TABLESPACE TO lem;
